import { z } from "zod";

export const orderCreateSchema = z.object({
  customerName: z.string(),
  customerRegion: z.string().optional().default(""),
  customerAddress: z.string().optional().default(""),
  productName: z.string(),
  productStatus: z.string().optional().default(""),
  upstreamContact: z.string().optional().default(""),
  priorityShipping: z.boolean().optional().default(false),
  isReturn: z.boolean().optional().default(false),
  salesStatus: z.string().optional().default(""),
  purchasePrice: z.coerce.number().optional().default(0),
  sellingPrice: z.coerce.number().optional().default(0),
  actualPayment: z.coerce.number().optional().default(0),
  packagingShipping: z.coerce.number().optional().default(0),
  returnPurchasePrice: z.coerce.number().optional().default(0),
  returnSellingPrice: z.coerce.number().optional().default(0),
  actualRefund: z.coerce.number().optional().default(0),
  returnPackagingCost: z.coerce.number().optional().default(0),
  ironFanBenefit: z.string().optional().default(""),
  diamondFanBenefit: z.string().optional().default(""),
  loyalFanBenefit: z.string().optional().default(""),
  superFanBenefit: z.string().optional().default(""),
  startDate: z.string().optional().default(""),
  completionDate: z.string().optional().default(""),
  remark: z.string().optional().default(""),
});

// 更新 schema：字段可选，不设默认值（避免把未传字段填成 0 或空字符串）
export const orderUpdateSchema = z.object({
  customerName: z.string().optional(),
  customerRegion: z.string().optional(),
  customerAddress: z.string().optional(),
  productName: z.string().optional(),
  productStatus: z.string().optional(),
  upstreamContact: z.string().optional(),
  priorityShipping: z.boolean().optional(),
  isReturn: z.boolean().optional(),
  salesStatus: z.string().optional(),
  purchasePrice: z.coerce.number().optional(),
  sellingPrice: z.coerce.number().optional(),
  actualPayment: z.coerce.number().optional(),
  packagingShipping: z.coerce.number().optional(),
  returnPurchasePrice: z.coerce.number().optional(),
  returnSellingPrice: z.coerce.number().optional(),
  actualRefund: z.coerce.number().optional(),
  returnPackagingCost: z.coerce.number().optional(),
  ironFanBenefit: z.string().optional(),
  diamondFanBenefit: z.string().optional(),
  loyalFanBenefit: z.string().optional(),
  superFanBenefit: z.string().optional(),
  startDate: z.string().optional(),
  completionDate: z.string().optional(),
  remark: z.string().optional(),
});
