-- CreateTable
CREATE TABLE "Order" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customer_name" TEXT NOT NULL,
    "customer_region" TEXT NOT NULL DEFAULT '',
    "customer_address" TEXT NOT NULL DEFAULT '',
    "product_name" TEXT NOT NULL,
    "product_status" TEXT NOT NULL DEFAULT '',
    "upstream_contact" TEXT NOT NULL DEFAULT '',
    "priority_shipping" BOOLEAN NOT NULL DEFAULT false,
    "is_return" BOOLEAN NOT NULL DEFAULT false,
    "sales_status" TEXT NOT NULL DEFAULT '',
    "purchase_price" REAL NOT NULL DEFAULT 0,
    "selling_price" REAL NOT NULL DEFAULT 0,
    "actual_payment" REAL NOT NULL DEFAULT 0,
    "packaging_shipping" REAL NOT NULL DEFAULT 0,
    "return_purchase_price" REAL NOT NULL DEFAULT 0,
    "return_selling_price" REAL NOT NULL DEFAULT 0,
    "actual_refund" REAL NOT NULL DEFAULT 0,
    "return_packaging_cost" REAL NOT NULL DEFAULT 0,
    "return_profit" REAL NOT NULL DEFAULT 0,
    "profit" REAL NOT NULL DEFAULT 0,
    "iron_fan_benefit" TEXT NOT NULL DEFAULT '',
    "diamond_fan_benefit" TEXT NOT NULL DEFAULT '',
    "loyal_fan_benefit" TEXT NOT NULL DEFAULT '',
    "super_fan_benefit" TEXT NOT NULL DEFAULT '',
    "start_date" TEXT NOT NULL DEFAULT '',
    "completion_date" TEXT NOT NULL DEFAULT '',
    "remark" TEXT NOT NULL DEFAULT '',
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL
);
